on:
  push:
    branches:
      - master

name: Run shelscript

jobs:
  shelscript:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: run-shel
        run: |
          sh ./hello.sh
          echo "AWS Cost in $(date '+%Y-%m') (JPY)"