on:
  push:
    branches:
      - master

name: Run shelscript

jobs:
  shelscript:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - uses: actions/checkout@v2
      - name: run-shel
        run: sh hello.sh